/**
 * This file was generated by the Jeddict
 */
package org.Rpedido.modelo;

import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * @author Ruan
 */
@Entity
public class Pedido {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Basic
    private String data;

    @Basic
    private String hora;

    @Basic
    private String observação;

    @Basic
    private String situação;

    @OneToMany(targetEntity = Objeto.class)
    private List<Objeto> objetoes;

    @OneToMany(targetEntity = Funcionario.class)
    private List<Funcionario> funcionarios;

    @OneToMany(targetEntity = Requerinte.class)
    private List<Requerinte> requerintes;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getHora() {
        return this.hora;
    }

    public void setHora(String hora) {
        this.hora = hora;
    }

    public String getObservação() {
        return this.observação;
    }

    public void setObservação(String observação) {
        this.observação = observação;
    }

    public String getSituação() {
        return this.situação;
    }

    public void setSituação(String situação) {
        this.situação = situação;
    }

    public List<Objeto> getObjetoes() {
        return this.objetoes;
    }

    public void setObjetoes(List<Objeto> objetoes) {
        this.objetoes = objetoes;
    }

    public List<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }

    public void setFuncionarios(List<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }

    public List<Requerinte> getRequerintes() {
        return this.requerintes;
    }

    public void setRequerintes(List<Requerinte> requerintes) {
        this.requerintes = requerintes;
    }

    @Override
    public String toString() {
        return "Pedido{" + "id=" + id + ", data=" + data + ", hora=" + hora + ", observa\u00e7\u00e3o=" + observação + ", situa\u00e7\u00e3o=" + situação + ", objetoes=" + objetoes + ", funcionarios=" + funcionarios + ", requerintes=" + requerintes + '}';
    }
    
    

}
